export const boundaryGame = {
  id: "boundary",
  title: "版图 345",
  eyebrow: "Boundary 345",
  shareName: "版图 345",
  mapMode: "atlas",
  storageKey: "boundary-345-stats-v1",
  badgeIcon: "map",
  badgeDaily: "今日挑战",
  badgeRandom: "随机开局",
  mapLabel: "行政版图区域",
  cardSummary: "看行政区外轮廓、县区划分和驻地点猜城。",
  initialIcon: "map",
  initialTitle: "正在加载行政版图",
  initialText: "观察外轮廓、县区划分和政府驻地分布。",
  progressText: () => "，版图保持不变，继续对照轮廓、县区和驻地点。",
  loadFailTitle: "版图连接失败",
  loadFailText: "行政区边界暂时没有加载成功。",
  taiwanTownBoundaryByCode: {
    710100: "assets/taiwan-towns-63000.topo.json",
    710200: "assets/taiwan-towns-65000.topo.json",
    710300: "assets/taiwan-towns-68000.topo.json",
    710400: "assets/taiwan-towns-66000.topo.json",
    710500: "assets/taiwan-towns-67000.topo.json",
    710600: "assets/taiwan-towns-64000.topo.json",
  },
};
