export const cabbageGame = {
  id: "cabbage",
  title: "白菜 345",
  eyebrow: "Cabbage 345",
  shareName: "白菜 345",
  mapMode: "terrain",
  storageKey: "cabbage-345-stats-v1",
  badgeIcon: "sprout",
  badgeDaily: "今日挑战",
  badgeRandom: "随机开局",
  mapLabel: "地形图区域",
  cardSummary: "看绿色阴影地形和城市轮廓猜城。",
  initialIcon: "sprout",
  initialTitle: "百菜不如白菜",
  initialText: "观察山脊、河谷、平原和行政轮廓。",
  progressText: () => "，地形图保持不变，继续对照山脉、河谷和平原。",
  loadFailTitle: "地形连接失败",
  loadFailText: "地形或行政边界暂时没有加载成功。",
};
