export const skyeyeGame = {
  id: "skyeye",
  title: "天眼 345",
  eyebrow: "Skyeye 345",
  shareName: "天眼 345",
  mapMode: "satellite",
  storageKey: "skyeye-345-stats-v1",
  badgeIcon: "satellite",
  badgeDaily: "今日挑战",
  badgeRandom: "随机开局",
  mapLabel: "卫星影像区域",
  cardSummary: "从无标注卫星图识别中国 345 城。",
  initialIcon: "radar",
  initialTitle: "正在接收卫星影像",
  initialText: "观察城市肌理、河流、海岸和山地轮廓。",
  progressText: (stepLabel) => `，视野已扩大到${stepLabel}。`,
  loadFailTitle: "底图连接失败",
  loadFailText: "请检查网络后刷新页面。",
};
